--01
CREATE TABLE CYTATY AS SELECT * FROM ZSBD_TOOLS.CYTATY;

--02
SELECT AUTOR, TEKST FROM CYTATY
WHERE UPPER(TEKST) LIKE '%PESYMISTA%' AND UPPER(TEKST) LIKE '%OPTYMISTA%';

--03
CREATE INDEX CYTATY_TEKST_IDX ON CYTATY(TEKST) INDEXTYPE IS CTXSYS.CONTEXT;

--04
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'PESYMISTA AND OPTYMISTA', 1) > 0;

--05
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'PESYMISTA ~ OPTYMISTA', 1) > 0;

--06
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'NEAR((PESYMISTA, OPTYMISTA), 3)') > 0;

--07
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'NEAR((PESYMISTA, OPTYMISTA), 10)') > 0;

--08
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%', 1) > 0;

--09
SELECT AUTOR, TEKST, SCORE(1) AS DOPASOWANIE
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%', 1) > 0;

--10
SELECT AUTOR, TEKST, SCORE(1) AS DOPASOWANIE
FROM CYTATY
WHERE CONTAINS(TEKST, 'życi%', 1) > 0 AND ROWNUM = 1
ORDER BY 3 DESC

--11
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'FUZZY(PROBLEM,,,N)', 1) > 0;

--12
INSERT INTO CYTATY VALUES(
    -1,
    'Bertrand Russell',
    'To smutne, że głupcy są tacy pewni siebie, a ludzie rozsądni tacy pełni wątpliwości.'
);
COMMIT;

--13
SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'GłUPCY', 1) > 0;
-- Brak synchronizacji

--14
SELECT TOKEN_TEXT FROM DR$CYTATY_TEKST_IDX$I WHERE TOKEN_TEXT = 'GŁUPCY';

--15
DROP INDEX CYTATY_TEKST_IDX;
CREATE INDEX CYTATY_TEKST_IDX ON CYTATY(TEKST) INDEXTYPE IS CTXSYS.CONTEXT;

--16
SELECT TOKEN_TEXT FROM DR$CYTATY_TEKST_IDX$I WHERE TOKEN_TEXT = 'GŁUPCY';

SELECT AUTOR, TEKST
FROM CYTATY
WHERE CONTAINS(TEKST, 'GłUPCY', 1) > 0;

--17
DROP INDEX CYTATY_TEKST_IDX;
DROP TABLE CYTATY;
